// Build step: extract the clean prompt text from prompts/*.md (the content
// between the first pair of ``` fences) and emit prompts.js with the prompts as
// JSON-escaped string globals the frontend loads.
//
// Keeping the .md files as the single source of truth means prompt edits happen
// in readable Markdown, and `node build-prompts.js` regenerates the frontend copy.
// JSON.stringify handles all escaping (newlines, quotes, backslashes); backticks
// pass through fine because prompts.js uses double-quoted strings.

const fs = require('fs');
const path = require('path');

const PROMPTS = [
  { file: 'promptA-interview-v5.md', global: 'PROMPT_A' },
  { file: 'promptB-scoring-v5.md', global: 'PROMPT_B' },
  { file: 'promptC-skills-v2.md', global: 'PROMPT_C' },
  { file: 'promptD-skills-scoring-v2.md', global: 'PROMPT_D' }
];

function extractFenced(file) {
  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
  const fences = [];
  lines.forEach((l, i) => { if (l.trim() === '```') fences.push(i); });
  if (fences.length < 2) throw new Error(`Expected a fenced block in ${file}`);
  return lines.slice(fences[0] + 1, fences[1]).join('\n').trim();
}

const dir = __dirname;
let out = '// AUTO-GENERATED by build-prompts.js — do not edit by hand.\n// Source of truth: prompts/*.md   Regenerate: node build-prompts.js\n';
const sizes = [];
PROMPTS.forEach(p => {
  const text = extractFenced(path.join(dir, 'prompts', p.file));
  out += `window.${p.global} = ${JSON.stringify(text)};\n`;
  sizes.push(`${p.global}: ${text.length}`);
});
fs.writeFileSync(path.join(dir, 'prompts.js'), out);
console.log('prompts.js written —', sizes.join(', '));

// Sanity checks.
const A = extractFenced(path.join(dir, 'prompts', 'promptA-interview-v5.md'));
// v5 note: Q4's horizon is chosen by the model from {{TEEN_AGE}}, so {{TEEN_AGE_PLUS_3}}
// is no longer required in Prompt A.
['{{TEEN_FIRST_NAME}}', '{{PARENT_FIRST_NAME}}', '{{TEEN_AGE}}'].forEach(ph => {
  if (!A.includes(ph)) console.warn(`WARNING: Prompt A is missing placeholder ${ph}`);
});
if (!A.includes('[INTERVIEW_COMPLETE]')) console.warn('WARNING: Prompt A missing [INTERVIEW_COMPLETE]');
const C = extractFenced(path.join(dir, 'prompts', 'promptC-skills-v2.md'));
if (!C.includes('[SKILLS_COMPLETE]')) console.warn('WARNING: Prompt C missing [SKILLS_COMPLETE]');
