// Build step: extract the clean prompt text from prompts/*.md (the content
// between the first pair of ``` fences) and emit prompts.js with the two
// prompts as JSON-escaped string globals the frontend loads.
//
// Keeping the .md files as the single source of truth means prompt edits happen
// in readable Markdown, and `node build-prompts.js` regenerates the frontend copy.
// JSON.stringify handles all escaping (newlines, quotes, backslashes); backticks
// pass through fine because prompts.js uses double-quoted strings, not template
// literals.

const fs = require('fs');
const path = require('path');

function extractFenced(file) {
  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
  const fences = [];
  lines.forEach((l, i) => { if (l.trim() === '```') fences.push(i); });
  if (fences.length < 2) throw new Error(`Expected a fenced block in ${file}`);
  return lines.slice(fences[0] + 1, fences[1]).join('\n').trim();
}

const dir = __dirname;
const A = extractFenced(path.join(dir, 'prompts', 'promptA-interview-v4.md'));
const B = extractFenced(path.join(dir, 'prompts', 'promptB-scoring-v4.md'));

const out =
`// AUTO-GENERATED by build-prompts.js — do not edit by hand.
// Source of truth: prompts/promptA-interview-v4.md and prompts/promptB-scoring-v4.md
// Regenerate: node build-prompts.js
window.PROMPT_A = ${JSON.stringify(A)};
window.PROMPT_B = ${JSON.stringify(B)};
`;

fs.writeFileSync(path.join(dir, 'prompts.js'), out);
console.log(`prompts.js written — Prompt A: ${A.length} chars, Prompt B: ${B.length} chars`);

// Sanity: the placeholders the frontend substitutes must exist in Prompt A.
['{{TEEN_FIRST_NAME}}', '{{PARENT_FIRST_NAME}}', '{{TEEN_AGE}}', '{{TEEN_AGE_PLUS_3}}'].forEach(ph => {
  if (!A.includes(ph)) console.warn(`WARNING: Prompt A is missing placeholder ${ph}`);
});
if (!A.includes('[INTERVIEW_COMPLETE]')) console.warn('WARNING: Prompt A missing [INTERVIEW_COMPLETE] sentinel');
['[SAFETY_EVENT:CRISIS]', '[SAFETY_EVENT:ABUSE]', '[SAFETY_EVENT:SUPPORT]'].forEach(s => {
  if (!A.includes(s)) console.warn(`WARNING: Prompt A missing safety sentinel ${s}`);
});
